<?php
/**
 * The one agency this Connector trusts. Generated by bin/build.sh on 2026-09-29.
 *
 * @package CPub\Connector
 */

return array (
  'client_id' => 'cpub-publisher',
  'name' => 'Agency',
  'url' => 'https://carryshape.s3-tastewp.com',
  'logo' => '',
  'redirect_uris' => 
  array (
    0 => 'https://carryshape.s3-tastewp.com/wp-admin/admin.php?page=cpub-publisher&cpub_oauth=callback',
    1 => 'http://127.0.0.1/callback',
  ),
);
