<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'CPub\\Publisher\\Vendor\\Symfony\\Polyfill\\Php80\\' => array($vendorDir . '/symfony/polyfill-php80'),
    'CPub\\Publisher\\Vendor\\Psr\\EventDispatcher\\' => array($vendorDir . '/psr/event-dispatcher/src'),
    'CPub\\Publisher\\Vendor\\Nette\\' => array($vendorDir . '/nette/schema/src', $vendorDir . '/nette/utils/src'),
    'CPub\\Publisher\\Vendor\\League\\Config\\' => array($vendorDir . '/league/config/src'),
    'CPub\\Publisher\\Vendor\\League\\CommonMark\\' => array($vendorDir . '/league/commonmark/src'),
    'CPub\\Publisher\\Vendor\\Dflydev\\DotAccessData\\' => array($vendorDir . '/dflydev/dot-access-data/src'),
);
