<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    '6b07ccdd585d908ce3dac85be04f34c0' => $vendorDir . '/symfony/deprecation-contracts/function.php',
    '9e3015fe6e1c5d92962210a61d6c3f81' => $vendorDir . '/symfony/polyfill-php80/bootstrap.php',
);
