<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitdd50008ec4767a00f15ed9dc8486498d
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('CPub\Publisher\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \CPub\Publisher\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInitdd50008ec4767a00f15ed9dc8486498d', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \CPub\Publisher\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitdd50008ec4767a00f15ed9dc8486498d', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\CPub\Publisher\Vendor\Composer\Autoload\ComposerStaticInitdd50008ec4767a00f15ed9dc8486498d::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        $filesToLoad = \CPub\Publisher\Vendor\Composer\Autoload\ComposerStaticInitdd50008ec4767a00f15ed9dc8486498d::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }

        return $loader;
    }
}
