<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'CPub\\Connector\\Vendor\\Psr\\Http\\Server\\' => array($vendorDir . '/psr/http-server-middleware/src', $vendorDir . '/psr/http-server-handler/src'),
    'CPub\\Connector\\Vendor\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'),
    'CPub\\Connector\\Vendor\\Psr\\EventDispatcher\\' => array($vendorDir . '/psr/event-dispatcher/src'),
    'CPub\\Connector\\Vendor\\Psr\\Clock\\' => array($vendorDir . '/psr/clock/src'),
    'CPub\\Connector\\Vendor\\Nyholm\\Psr7\\' => array($vendorDir . '/nyholm/psr7/src'),
    'CPub\\Connector\\Vendor\\League\\Uri\\' => array($vendorDir . '/league/uri', $vendorDir . '/league/uri-interfaces'),
    'CPub\\Connector\\Vendor\\League\\OAuth2\\Server\\' => array($vendorDir . '/league/oauth2-server/src'),
    'CPub\\Connector\\Vendor\\League\\Event\\' => array($vendorDir . '/league/event/src'),
    'CPub\\Connector\\Vendor\\Lcobucci\\JWT\\' => array($vendorDir . '/lcobucci/jwt/src'),
    'CPub\\Connector\\Vendor\\Defuse\\Crypto\\' => array($vendorDir . '/defuse/php-encryption/src'),
);
