<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit6bf8bb7ae7ca75d10b52654c07e6d0a8
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('CPub\Connector\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \CPub\Connector\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInit6bf8bb7ae7ca75d10b52654c07e6d0a8', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \CPub\Connector\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit6bf8bb7ae7ca75d10b52654c07e6d0a8', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\CPub\Connector\Vendor\Composer\Autoload\ComposerStaticInit6bf8bb7ae7ca75d10b52654c07e6d0a8::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
